version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-scheduler
    restart: always
    shm_size: '1gb'
    environment:
      - USER_TOKEN=${USER_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - ./config.json:/app/config.json
      - ./log_user.txt:/app/log_user.txt
      - discord_browser_data:/app/discord_browser_data

volumes:
  discord_browser_data:
